### ISSUE TITLE
AzureDiagnosticsPipeline Error

### ISSUE THREAD

**Issue by dnyaneshgaike** [JimGBritt/AzureDiagnosticsPipeline#1]
Hi Jim,

I have followed the steps of AzureDiagnosticsPipeline under our Azure DevOps dev environment but after completing setup when we are trying to run this pipeline we are getting error at "Deploy_Diagnostics_Initiative..." & "Assign_Role_To_Initiative..." we tried to troubleshoot but still getting same error. Please refer attached image and let me know if anything missing our side. Thanks.
![image](https://user-images.githubusercontent.com/82099137/113870171-2df53080-97cf-11eb-9567-76d1d6aff359.png)

**Comment by JimGBritt** [comment]
Very sorry for my delay in response here @dnyaneshgaike .  The error indicates that you are trying to update a policy initiative that is already in place with new parameters potentially.  It may be due to the fact that the existing has a regional option or ability to select regions or vice versa.  Please take a look at the section in the documentation that indicates where you should update the command line parameters for the main script for creating the policy / policy initiative to make sure those options are not in conflict with an existing deployment.  In addition, you definitely want to review if you have anything already deployed in general as you do not want this pipeline to impact that deployment and configuration.  Ensure you are testing in a test / sandbox environment to see how this interacts and deploys before moving to production.

**Comment by JimGBritt** [comment]
@dnyaneshgaike I am going to have to assume this one is closed out - please re-open if you are still seeing challenges and we can manage through that issue.

**Comment by dnyaneshgaike** [comment]
Sure Jim Britt, thanks.

________________________________
